### PR TITLE
[app-misc/fluxgui] Add libappindicator[python] dependency

### PR DESCRIPTION
**Pull request by zamabe**
~~Slot :2 is the one fluxgui searches for, depend on it.~~  
fluxgui needs libappindicator with python bindings

### CODE REVIEW

**Comment by and3k** [comment]
I’m not sure we should add a hard dependency for libappindicator, because the ebuild also works without it. See https://github.com/and3k/and3k-sunrise/issues/1.

Maybe this would need a USE flag? What do you think, @aaferrari?

Thanks,
Bela

**Comment by zamabe** [comment]
The *ebuild* would work without it, but the application itself won't because its dependency on it isn't expressed until runtime; so the ebuild will have succeeded in installing an application which will not run.

**Comment by and3k** [comment]
The idea is, that the ebuild will also install without libappindicator, and that it then also work without it. Which is currently should do. See patch in src_prepare.

Isn’t RDEPEND required to be installed for the ebuild to work? So add the libappindicator would break the above behaviour?

**Comment by zamabe** [comment]
> ... then also work without it. Which is currently should do.

But... it doesn't. :/

**Comment by aaferrari** [comment]
>I’m not sure we should add a hard dependency for libappindicator, because the ebuild also works without it. See #1.
>
>Maybe this would need a USE flag? What do you think, @aaferrari?

At that moment add the libappindicator replacement because the library did not install the Python bindings (the only version that had was the [Unity overlay](https://github.com/shiznix/unity-gentoo)), then it seems that a few weeks after [was readded in libappindicator-12.10.0-r200](https://bugs.gentoo.org/show_bug.cgi?id=512976) and I did not realize.
Initially should be sufficient with `dev-libs/libappindicator:2[python]` and remove the patch but if one day remove the bindings (not be [the first time](https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-libs/libappindicator/libappindicator-12.10.0-r2.ebuild?hideattic=0&revision=1.1&view=markup)) then the ebuild could become unusable. One way to deal with this would be add in the first `if` a check to determine if libappindicator has not the `python` USE flag (though I do not know how to do this in the ebuild).
By the way, before merge this pull request (and if it is finally decided to keep the first `if`) I would like that @zamabe change `python -m appindicator` by `python -c "import appindicator"` because `python -m` always fails (even with the module available).

>As for #1, I mean, yeah, that'd be nice. It could run without libappindicator, but it presently does not.
>
>Gnome 3.18.3 here

----

>>... then also work without it. Which is currently should do.
>
>But... it doesn't. :/

Well I upgrade GTK 2 and 3 a few weeks ago to versions 2.24.29 and 3.18.7 respectively and so far the program works as usual (with and without libappindicator replacement). Except for a few warnings about the icons at the beginning, I have not encountered major problems so far. If you give more details on these problems that you have perhaps I can correct the patch.

**Comment by zamabe** [comment]
> Initially should be sufficient with dev-libs/libappindicator:2[python]

`libappindicator:2` is the only one with a python flag, so it is also sufficient to use `dev-libs/libappindicator[python]`, which would reasonably guarantee python bindings.

**Comment by zamabe** [comment]
Apologies for the mess just above. Github will clean it up some time within a week.

**Comment by zamabe** [comment]
Also, the test is probably flawed. `python` is going to be system python which is python3 for me, but python2 is the target of both. Just going to `s/python/python2/` in the test you've asked me to change.

**Comment by aaferrari** [comment]
>I'm afraid modifying your patches is a bit over my head, though I will add this change to my pull request and change libappindicator to a python use flag. Should this bump the ebuild to -r3?

Normally I do so for that the changes will reach anyone with the installed program when updating the system, although and3k has the last word on this. `;-)`

>It complains about a failed import, same as #1. I don't know what information would be helpful to you. I'm still using the ebuild as is, not with my edits; I've just installed this dependency myself which restored working functionality.

With copy and paste what you appears when you run the program from a console could give me a better idea of what happens. In my case I get the following:
```
/usr/lib/python2.7/site-packages/fluxgui/fluxapp.py:104: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type GdkColor

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/lib/python2.7/site-packages/fluxgui/fluxapp.py:104: Warning: g_value_unset: assertion 'G_IS_VALUE (value)' failed
  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/lib/python2.7/site-packages/fluxgui/fluxapp.py:104: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
```
Really is not anything serious because the program is operating normally, though may have be related with the GTK+ updates that I mentioned above (if you happen the same then can leave a issue in the [new official repository]()).

>Do your patches depend on anything not in the ebuild deps? :/ Perhaps a switch on gnome use flag for deps, or some other flag, would be easier to cover all cases.

Well, [appindicator_replacement.py](https://github.com/and3k/and3k-sunrise/blob/master/app-misc/fluxgui/files/fluxgui-1.1.8-appindicator.patch) needs dev-python/pygtk and dev-python/pygobject to run (not had that into account as they in its time did not see it necessary and imagine that would be installed by other programs, I apologize for that omission). Try installing these packages with `emerge -1 dev-python/pygtk dev-python/pygobject` and run the program using `appindicator_replacement` to see if your problem is due to that. If it works thus, maybe it could include PyGTK and PyGObject as extra dependencies within this `if` (though I do not know how).

**Comment by zamabe** [comment]
> copy and paste what you appears when you run the program from a console could give me a better idea of what happens.

```
~> cat /etc/portage/sets/fluxgui-deps
dev-python/gconf-python
dev-libs/libappindicator:2

~> emerge -c @fluxgui-deps
<snip>

~> emerge fluxgui
<snip>

~> fluxgui
Traceback (most recent call last):
  File "~/.local/lib64/python2.7/site-packages/fluxgui/fluxapp.py", line 3, in <module>
    from fluxgui import fluxcontroller, settings
  File "~/.local/lib64/python2.7/site-packages/fluxgui/settings.py", line 2, in <module>
    import gconf
ImportError: No module named gconf

~> emerge -1 dev-python/gconf-python
<snip>

~> fluxgui
Traceback (most recent call last):
  File "~/.local/lib64/python2.7/site-packages/fluxgui/fluxapp.py", line 7, in <module>
    import appindicator
ImportError: No module named appindicator

~> emerge -1 dev-libs/libappindicator:2
<snip>

~> fluxgui
~/.local/lib64/python2.7/site-packages/fluxgui/fluxapp.py:100: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type GdkColor

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
~/.local/lib64/python2.7/site-packages/fluxgui/fluxapp.py:100: Warning: g_value_unset: assertion 'G_IS_VALUE (value)' failed
  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
~/.local/lib64/python2.7/site-packages/fluxgui/fluxapp.py:100: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint
```

Only the last attempt works.

**Comment by zamabe** [comment]
> Try installing these packages with emerge -av1 dev-python/pygtk dev-python/pygobject:2 and run the program using appindicator_replacement to see if your problem is due to that.

```
~> emerge -c @fluxgui-deps
<snip>

~> cat /etc/portage/sets/fluxgui-deps-2
dev-python/pygtk
dev-python/pygobject:2

~> emerge @fluxgui-deps-2
<snip>

~> emerge fluxgui
<snip>

~> fluxgui
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/fluxgui/fluxapp.py", line 3, in <module>
    from fluxgui import fluxcontroller, settings
  File "/usr/lib64/python2.7/site-packages/fluxgui/settings.py", line 2, in <module>
    import gconf
ImportError: No module named gconf

~> emerge -1 dev-python/gconf-python
<snip>

~> fluxgui
/usr/lib64/python2.7/site-packages/fluxgui/fluxapp.py:104: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type GdkColor

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/lib64/python2.7/site-packages/fluxgui/fluxapp.py:104: Warning: g_value_unset: assertion 'G_IS_VALUE (value)' failed
  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
/usr/lib64/python2.7/site-packages/fluxgui/fluxapp.py:104: GtkWarning: Cannot transform xsetting Net/IconThemeName of type gchararray to type gint

  gtk.gdk.screen_get_default().get_setting('gtk-icon-theme-name')
^C
```

wat

**Comment by zamabe** [comment]
So, found my dumb. `~/.local/lib64/python2.7/site-packages/fluxgui/`

**Comment by zamabe** [comment]
Though, it does still lack a dep on `dev-python/gconf-python`, and `s/python -m appindicator/python2 -c "import appindicator"/`

**Pull request closed without merging**
